<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC9_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Current_Product_List
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC9_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Current_Product_List
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
    }
}
>>>>>>> b085a125942dd55cc881c5d912888ae618f5dee9
