//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReserveSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MiniProject_RailwayEntities : DbContext
    {
        public MiniProject_RailwayEntities()
            : base("name=MiniProject_RailwayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<train> trains { get; set; }
        public virtual DbSet<TrainClassInfo> TrainClassInfoes { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<CancelTicket> CancelTickets { get; set; }
    
        public virtual int AddTrain(Nullable<int> trainID, string trainName, string source, string destination)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            var trainNameParameter = trainName != null ?
                new ObjectParameter("TrainName", trainName) :
                new ObjectParameter("TrainName", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddTrain", trainIDParameter, trainNameParameter, sourceParameter, destinationParameter);
        }
    
        public virtual int AddTrainClassInfo(Nullable<int> trainID, string @class, Nullable<int> totalSeats, Nullable<decimal> price)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            var classParameter = @class != null ?
                new ObjectParameter("Class", @class) :
                new ObjectParameter("Class", typeof(string));
    
            var totalSeatsParameter = totalSeats.HasValue ?
                new ObjectParameter("TotalSeats", totalSeats) :
                new ObjectParameter("TotalSeats", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddTrainClassInfo", trainIDParameter, classParameter, totalSeatsParameter, priceParameter);
        }
    
        public virtual int ModifyTrain(Nullable<int> trainID, string trainName, string source, string destination)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            var trainNameParameter = trainName != null ?
                new ObjectParameter("TrainName", trainName) :
                new ObjectParameter("TrainName", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifyTrain", trainIDParameter, trainNameParameter, sourceParameter, destinationParameter);
        }
    
        public virtual int SoftDeleteTrain(Nullable<int> trainID)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SoftDeleteTrain", trainIDParameter);
        }
    
        public virtual int ChangeTrainStatus(Nullable<int> trainID)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeTrainStatus", trainIDParameter);
        }
    
        public virtual ObjectResult<ViewTrainStatus_Result> ViewTrainStatus(Nullable<int> trainID)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewTrainStatus_Result>("ViewTrainStatus", trainIDParameter);
        }
    
        public virtual ObjectResult<ShowAllTrain_Result> ShowAllTrain()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowAllTrain_Result>("ShowAllTrain");
        }
    
        public virtual int InsertAdmin(Nullable<int> adminID, string username, Nullable<int> phonenumber, string password)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var phonenumberParameter = phonenumber.HasValue ?
                new ObjectParameter("Phonenumber", phonenumber) :
                new ObjectParameter("Phonenumber", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAdmin", adminIDParameter, usernameParameter, phonenumberParameter, passwordParameter);
        }
    
        public virtual int InsertUsers(Nullable<int> userID, string username, Nullable<int> phonenumber, string password)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var phonenumberParameter = phonenumber.HasValue ?
                new ObjectParameter("Phonenumber", phonenumber) :
                new ObjectParameter("Phonenumber", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUsers", userIDParameter, usernameParameter, phonenumberParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetActiveTrains_Result> GetActiveTrains()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveTrains_Result>("GetActiveTrains");
        }
    
        public virtual ObjectResult<GetBirthDetal_Result> GetBirthDetal(Nullable<int> trainID)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBirthDetal_Result>("GetBirthDetal", trainIDParameter);
        }
    
        public virtual ObjectResult<GetClassDetail_Result> GetClassDetail(Nullable<int> trainID)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClassDetail_Result>("GetClassDetail", trainIDParameter);
        }
    
        public virtual int BookTrainTicket(string userName, Nullable<int> trainID, string @class, Nullable<int> totalTickets)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            var classParameter = @class != null ?
                new ObjectParameter("Class", @class) :
                new ObjectParameter("Class", typeof(string));
    
            var totalTicketsParameter = totalTickets.HasValue ?
                new ObjectParameter("TotalTickets", totalTickets) :
                new ObjectParameter("TotalTickets", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BookTrainTicket", userNameParameter, trainIDParameter, classParameter, totalTicketsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetLastBookingID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetLastBookingID");
        }
    
        public virtual ObjectResult<GetTrainsByRoute_Result> GetTrainsByRoute(string source, string destination)
        {
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTrainsByRoute_Result>("GetTrainsByRoute", sourceParameter, destinationParameter);
        }
    
        public virtual ObjectResult<Printticket_Result> Printticket(Nullable<int> bookingID)
        {
            var bookingIDParameter = bookingID.HasValue ?
                new ObjectParameter("BookingID", bookingID) :
                new ObjectParameter("BookingID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Printticket_Result>("Printticket", bookingIDParameter);
        }
    
        public virtual int CancelTicketData(Nullable<int> bookingID)
        {
            var bookingIDParameter = bookingID.HasValue ?
                new ObjectParameter("BookingID", bookingID) :
                new ObjectParameter("BookingID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CancelTicketData", bookingIDParameter);
        }
    
        public virtual ObjectResult<TrainClassInfo> GetClassDetail1(Nullable<int> trainID)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrainClassInfo>("GetClassDetail1", trainIDParameter);
        }
    
        public virtual ObjectResult<TrainClassInfo> GetClassDetail1(Nullable<int> trainID, MergeOption mergeOption)
        {
            var trainIDParameter = trainID.HasValue ?
                new ObjectParameter("TrainID", trainID) :
                new ObjectParameter("TrainID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrainClassInfo>("GetClassDetail1", mergeOption, trainIDParameter);
        }
    }
}
